### ISSUE TITLE
Unprotected Access in All()

### ISSUE THREAD

**Issue by naveensrinivasan** [jftuga/ttlMap#2]
https://github.com/jftuga/TtlMap/blob/1e9219bd31794f520e2f2138ffa13f20a6e1898d/ttlMap.go#L118-L120

The `All()` method returns a direct reference to the internal map (m.m). 

Any caller can then modify the map without acquiring the mutex, leading to potential race conditions.

Returning a deep map copy instead of a direct reference could be a solution.

**Comment by gozeloglu** [comment]
It seems you are right. Copied map can be returned by using locks. I think using `RLock` and `RUnlock` will be more suitable.

**Comment by jftuga** [comment]
Could you please review this [commit](https://github.com/jftuga/TtlMap/commit/9f62fb5c01febf20323dd94f393397deb3c97a58) to see if this fixes the problem?

Thanks.
